using Darwin.Application.Orders.Commands;
using Darwin.Application.Extensions;
using Darwin.Application.Abstractions.Services;
using Darwin.Application.Billing;
using Darwin.Application.CRM.Commands;
using Darwin.Application.Notifications;
using Darwin.Infrastructure.Adapters.Time;
using Darwin.Infrastructure.Extensions;
using Darwin.Infrastructure.Media;
using Darwin.Worker;

var builder = Host.CreateApplicationBuilder(args);
builder.Services.AddApplication(builder.Configuration);
builder.Services.AddLocalization();
builder.Services.AddSingleton<IClock, SystemClock>();
builder.Services.Configure<MediaStorageOptions>(builder.Configuration.GetSection(MediaStorageOptions.SectionName));
builder.Services.AddConfiguredPersistence(builder.Configuration);
builder.Services.AddSharedHostingDataProtection(builder.Configuration);
builder.Services.AddIdentityInfrastructure();
builder.Services.AddObjectStorageInfrastructure(builder.Configuration);
builder.Services.AddNotificationsInfrastructure(builder.Configuration);
builder.Services.AddShippingProviderInfrastructure();
builder.Services.AddComplianceInfrastructure(builder.Configuration);
builder.Services.AddHttpClient();
builder.Services.Configure<InactiveReminderWorkerOptions>(builder.Configuration.GetSection("InactiveReminderWorker"));
builder.Services.Configure<EmailDispatchOperationWorkerOptions>(builder.Configuration.GetSection("EmailDispatchOperationWorker"));
builder.Services.Configure<ChannelDispatchOperationWorkerOptions>(builder.Configuration.GetSection("ChannelDispatchOperationWorker"));
builder.Services.Configure<ProviderCallbackWorkerOptions>(builder.Configuration.GetSection("ProviderCallbackWorker"));
builder.Services.Configure<ShipmentProviderOperationWorkerOptions>(builder.Configuration.GetSection("ShipmentProviderOperationWorker"));
builder.Services.Configure<WebhookDeliveryWorkerOptions>(builder.Configuration.GetSection("WebhookDeliveryWorker"));
builder.Services.Configure<InvoiceArchiveMaintenanceWorkerOptions>(builder.Configuration.GetSection("InvoiceArchiveMaintenanceWorker"));
builder.Services.Configure<VatValidationRetryWorkerOptions>(builder.Configuration.GetSection("VatValidationRetryWorker"));
builder.Services.AddScoped<ApplyDhlShipmentCreateOperationHandler>();
builder.Services.AddScoped<ApplyDhlShipmentLabelOperationHandler>();
builder.Services.AddScoped<ApplyShipmentCarrierEventHandler>();
builder.Services.AddScoped<ProcessStripeWebhookHandler>();
builder.Services.AddScoped<ProcessBrevoTransactionalEmailWebhookHandler>();
builder.Services.AddScoped<PurgeExpiredInvoiceArchivesHandler>();
builder.Services.AddScoped<RetryUnknownCustomerVatValidationBatchHandler>();
builder.Services.AddHostedService<EmailDispatchOperationBackgroundService>();
builder.Services.AddHostedService<ChannelDispatchOperationBackgroundService>();
builder.Services.AddHostedService<InactiveReminderBackgroundService>();
builder.Services.AddHostedService<ProviderCallbackBackgroundService>();
builder.Services.AddHostedService<ShipmentProviderOperationBackgroundService>();
builder.Services.AddHostedService<WebhookDeliveryBackgroundService>();
builder.Services.AddHostedService<InvoiceArchiveMaintenanceBackgroundService>();
builder.Services.AddHostedService<VatValidationRetryBackgroundService>();

var host = builder.Build();
host.Run();
